# Generated by Django 2.1.7 on 2019-03-26 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('href', models.CharField(max_length=255)),
                ('requiresLogin', models.BooleanField(default=True)),
                ('onlyDisplayIfLoggedOut', models.BooleanField(default=False)),
                ('requiredPermissions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='PortalItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=255)),
                ('href', models.CharField(max_length=255)),
                ('requiresLogin', models.BooleanField(default=True)),
                ('onlyDisplayIfLoggedOut', models.BooleanField(default=False)),
                ('requiredPermissions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='PortalMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
