# Generated by Django 2.1.7 on 2019-03-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_praas', '0002_auto_20190326_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalitem',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='portalitem',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
