# Generated by Django 2.1.5 on 2019-01-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmr_app', '0001_squashed_0004_auto_20190126_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrtask',
            name='extended_resolve',
            field=models.BooleanField(default=False),
        ),
    ]
