# Generated by Django 2.1.7 on 2019-03-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedDomains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseURL', models.CharField(max_length=100)),
                ('allow', models.BooleanField(default=True)),
            ],
        ),
    ]
