# Generated by Django 2.1.7 on 2019-04-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reverseproxyapp', '0002_auto_20190324_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='alloweddomain',
            name='https',
            field=models.BooleanField(default=True),
        ),
    ]
