# Generated by Django 2.1.7 on 2019-03-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('cover', models.ImageField(upload_to='')),
                ('path', models.FilePathField()),
                ('release_date', models.DateField()),
            ],
        ),
    ]
