# Generated by Django 2.1.7 on 2019-03-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooklibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='cover',
            field=models.ImageField(upload_to='covers'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='path',
            field=models.CharField(max_length=256),
        ),
    ]
