# Generated by Django 2.1.7 on 2019-03-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooklibrary', '0005_auto_20190315_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='googleBooksMetadata',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='isbn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='raw_metadata',
            field=models.TextField(blank=True, null=True),
        ),
    ]
