# Generated by Django 2.1.7 on 2019-03-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooklibrary', '0006_auto_20190315_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('stage', models.TextField()),
                ('full_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
