# Generated by Django 2.1.7 on 2019-03-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooklibrary', '0008_auto_20190315_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importrun',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
