# Generated by Django 2.1.7 on 2019-03-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooklibrary', '0009_auto_20190315_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='googleBooksMetaDataSuggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField()),
                ('book', models.ForeignKey(on_delete=None, to='ebooklibrary.BookModel')),
            ],
        ),
    ]
