# Generated by Django 2.1.7 on 2019-03-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooklibrary', '0010_googlebooksmetadatasuggestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='googleBooksMetadata',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='metaDataFromBook',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='metaDataFromGoogle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='googlebooksmetadatasuggestions',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlebooksmetadatasuggestions',
            name='genre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlebooksmetadatasuggestions',
            name='googleBooksID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlebooksmetadatasuggestions',
            name='isbn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlebooksmetadatasuggestions',
            name='release_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlebooksmetadatasuggestions',
            name='short_descr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlebooksmetadatasuggestions',
            name='thumbnailUrl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlebooksmetadatasuggestions',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googlebooksmetadatasuggestions',
            name='item',
            field=models.TextField(blank=True, null=True),
        ),
    ]
